const cover = (id: string) =>
  `https://images.unsplash.com/${id}?w=1200&q=80`;

export const DEMO_NEWS = [
  {
    id: 'a1000001-0001-4001-8001-000000000001',
    title: 'BGN Luncurkan Portal Sidak Pantau Terpadu SPPG',
    slug: 'bgn-luncurkan-portal-sidak-pantau-terpadu-sppg',
    category: 'berita_umum',
    content:
      '<p>Badan Gizi Nasional (BGN) resmi meluncurkan Portal Sidak Pantau Terpadu untuk memantau seluruh Satuan Pelayanan Pemenuhan Gizi (SPPG) di Indonesia. Platform ini memungkinkan publik mengakses hasil inspeksi, tindak lanjut, dan status kepatuhan dapur SPPG secara transparan.</p><p>Kepala BGN menegaskan bahwa digitalisasi sidak merupakan bagian dari komitmen memastikan Program Makan Bergizi Gratis (MBG) berjalan sesuai standar gizi dan keamanan pangan.</p>',
    coverImage: cover('photo-1556909114-f6e7ad7d3136'),
    regionId: '31',
    publishedAt: new Date('2026-06-28T08:00:00Z'),
    status: 'published' as const,
    isHighlight: true,
    isBreaking: true,
    tags: ['bgn', 'sppg', 'sidak', 'mbg'],
  },
  {
    id: 'a1000002-0002-4002-8002-000000000002',
    title: 'Sidak Mendadak di 50 Dapur SPPG Jabodetabek',
    slug: 'sidak-mendadak-50-dapur-sppg-jabodetabek',
    category: 'sidak',
    content:
      '<p>Tim inspeksi BGN melaksanakan sidak mendadak ke 50 dapur SPPG di wilayah Jabodetabek pada pekan ini. Pemeriksaan fokus pada higienitas area produksi, penyimpanan bahan pangan, dan kesesuaian menu dengan standar gizi MBG.</p><p>Sebagian besar dapur dinilai memenuhi standar, namun beberapa temuan minor terkait dokumentasi harian dan sanitasi peralatan masih perlu ditindaklanjuti.</p>',
    coverImage: cover('photo-1600891964092-4316c288032e'),
    regionId: '31',
    publishedAt: new Date('2026-06-27T10:30:00Z'),
    status: 'published' as const,
    isHighlight: true,
    isBreaking: false,
    tags: ['sidak', 'sppg', 'jabodetabek', 'mbg'],
  },
  {
    id: 'a1000003-0003-4003-8003-000000000003',
    title: 'Evaluasi Nutrisi Menu MBG Semester I 2026',
    slug: 'evaluasi-nutrisi-menu-mbg-semester-i-2026',
    category: 'laporan',
    content:
      '<p>BGN merilis hasil evaluasi nutrisi menu Program MBG untuk semester pertama 2026. Kajian menilai kandungan energi, protein, lemak, dan mikronutrien pada menu yang disajikan di lebih dari 8.000 dapur SPPG.</p><p>Secara umum, 92% menu telah memenuhi ambang batas gizi yang ditetapkan. Rekomendasi perbaikan difokuskan pada variasi sayur dan buah lokal di wilayah timur Indonesia.</p>',
    coverImage: cover('photo-1498837167922-ddd27525d352'),
    regionId: null,
    publishedAt: new Date('2026-06-26T09:00:00Z'),
    status: 'published' as const,
    isHighlight: false,
    isBreaking: false,
    tags: ['mbg', 'gizi', 'evaluasi', 'bgn'],
  },
  {
    id: 'a1000004-0004-4004-8004-000000000004',
    title: 'BGN Terbitkan Standar Higienitas Baru untuk Dapur SPPG',
    slug: 'bgn-standar-higienitas-baru-dapur-sppg',
    category: 'berita_umum',
    content:
      '<p>Badan Gizi Nasional menerbitkan pedoman higienitas terbaru yang wajib diterapkan seluruh dapur SPPG mulai Juli 2026. Standar baru mencakup protokol sanitasi peralatan, pengelolaan limbah, dan pemantauan suhu penyimpanan bahan pangan.</p><p>Pedoman ini disusun berdasarkan temuan sidak nasional dan masukan dari ahli keamanan pangan serta gizi klinis.</p>',
    coverImage: cover('photo-1504674900247-0877df9cc836'),
    regionId: null,
    publishedAt: new Date('2026-06-25T14:00:00Z'),
    status: 'published' as const,
    isHighlight: true,
    isBreaking: false,
    tags: ['bgn', 'sppg', 'higienitas', 'standar'],
  },
  {
    id: 'a1000005-0005-4005-8005-000000000005',
    title: 'Hasil Sidak: 95% Dapur SPPG Jawa Barat Memenuhi Standar',
    slug: 'hasil-sidak-95-persen-sppg-jawa-barat',
    category: 'sidak',
    content:
      '<p>Inspeksi rutin BGN di Jawa Barat menunjukkan tingkat kepatuhan yang meningkat. Dari 320 dapur SPPG yang disidak, 95% dinyatakan memenuhi standar keamanan pangan dan gizi Program MBG.</p><p>Admin wilayah Jawa Barat menyatakan peningkatan ini hasil pembinaan berkelanjutan dan pelatihan petugas dapur sejak awal tahun.</p>',
    coverImage: cover('photo-1466637574441-749b8f19452f'),
    regionId: '32',
    publishedAt: new Date('2026-06-24T11:00:00Z'),
    status: 'published' as const,
    isHighlight: false,
    isBreaking: false,
    tags: ['sidak', 'sppg', 'jawa-barat', 'mbg'],
  },
  {
    id: 'a1000006-0006-4006-8006-000000000006',
    title: 'Pelatihan Petugas SPPG di 34 Provinsi Dimulai',
    slug: 'pelatihan-petugas-sppg-34-provinsi',
    category: 'berita_umum',
    content:
      '<p>BGN memulai program pelatihan nasional bagi petugas dapur SPPG di seluruh 34 provinsi. Materi meliputi pengolahan makanan bergizi, keamanan pangan, dan pencatatan hasil sidak mandiri.</p><p>Targetnya, setiap dapur SPPG memiliki minimal dua petugas tersertifikasi pada akhir 2026.</p>',
    coverImage: cover('photo-1556910103-1c02745aae4d'),
    regionId: null,
    publishedAt: new Date('2026-06-23T08:30:00Z'),
    status: 'published' as const,
    isHighlight: false,
    isBreaking: false,
    tags: ['sppg', 'pelatihan', 'bgn', 'mbg'],
  },
  {
    id: 'a1000007-0007-4007-8007-000000000007',
    title: 'Kajian Kelayakan Gizi Program MBG di Sekolah Dasar',
    slug: 'kajian-kelayakan-gizi-mbg-sekolah-dasar',
    category: 'laporan',
    content:
      '<p>Tim peneliti BGN menyelesaikan kajian kelayakan gizi Program MBG di 500 sekolah dasar percontohan. Studi membandingkan status gizi siswa sebelum dan setelah tiga bulan penerimaan makanan dari dapur SPPG setempat.</p><p>Hasil awal menunjukkan peningkatan indeks massa tubuh dan kehadiran siswa, meski variasi antarwilayah masih signifikan.</p>',
    coverImage: cover('photo-1506086679520-0b0955a13161'),
    regionId: '33',
    publishedAt: new Date('2026-06-22T13:00:00Z'),
    status: 'published' as const,
    isHighlight: false,
    isBreaking: false,
    tags: ['mbg', 'gizi', 'kajian', 'sekolah'],
  },
  {
    id: 'a1000008-0008-4008-8008-000000000008',
    title: 'Sidak Rutin MBG di Surabaya Temukan Perbaikan Minor',
    slug: 'sidak-rutin-mbg-surabaya-perbaikan-minor',
    category: 'sidak',
    content:
      '<p>Tim inspeksi BGN melakukan sidak rutin ke 18 dapur SPPG di Surabaya. Mayoritas dapur dinilai baik, dengan temuan minor terkait label kedaluwarsa bumbu kemasan dan kelengkapan APD petugas.</p><p>Rekomendasi perbaikan telah disampaikan dan tindak lanjut dijadwalkan dalam dua minggu.</p>',
    coverImage: cover('photo-1574489446809-78f9ab46a7d2'),
    regionId: '35',
    publishedAt: new Date('2026-06-21T09:45:00Z'),
    status: 'published' as const,
    isHighlight: false,
    isBreaking: false,
    tags: ['sidak', 'sppg', 'surabaya', 'mbg'],
  },
  {
    id: 'a1000009-0009-4009-8009-000000000009',
    title: 'BGN dan Kemendikdasmen Sinergi Awasi Kualitas MBG',
    slug: 'bgn-kemendikdasmen-sinergi-kualitas-mbg',
    category: 'berita_umum',
    content:
      '<p>Badan Gizi Nasional menandatangani nota kesepahaman dengan Kementerian Pendidikan Dasar dan Menengah untuk pengawasan bersama kualitas Program MBG di lingkungan sekolah.</p><p>Kolaborasi ini mencakup pelaporan temuan sidak SPPG, mekanisme pengaduan warga, dan evaluasi berkala dampak gizi siswa.</p>',
    coverImage: cover('photo-1523050854058-8df90110c9f1'),
    regionId: null,
    publishedAt: new Date('2026-06-20T10:00:00Z'),
    status: 'published' as const,
    isHighlight: false,
    isBreaking: true,
    tags: ['bgn', 'mbg', 'sinergi', 'pendidikan'],
  },
  {
    id: 'a1000010-0010-4010-8010-000000000010',
    title: 'Laporan Evaluasi Dampak MBG terhadap Status Gizi Anak',
    slug: 'laporan-evaluasi-dampak-mbg-status-gizi-anak',
    category: 'laporan',
    content:
      '<p>BGN mempublikasikan laporan evaluasi dampak Program MBG terhadap status gizi anak usia sekolah di 12 provinsi prioritas. Data dikumpulkan dari pemeriksaan antropometri dan wawancara dengan guru serta orang tua.</p><p>Laporan merekomendasikan penyesuaian porsi di wilayah dengan prevalensi stunting tinggi serta penguatan edukasi gizi keluarga.</p>',
    coverImage: cover('photo-1488521787991-ed7bbaae773c'),
    regionId: null,
    publishedAt: new Date('2026-06-19T08:00:00Z'),
    status: 'published' as const,
    isHighlight: false,
    isBreaking: false,
    tags: ['mbg', 'gizi', 'evaluasi', 'anak'],
  },
  {
    id: 'a1000011-0011-4011-8011-000000000011',
    title: 'Operasional 1.000 Dapur SPPG Baru Ditargetkan Q3 2026',
    slug: 'operasional-1000-dapur-sppg-baru-q3-2026',
    category: 'berita_umum',
    content:
      '<p>BGN menargetkan 1.000 dapur SPPG baru beroperasi pada kuartal III 2026 untuk memperluas cakupan Program MBG. Pembangunan difokuskan di daerah 3T dan wilayah dengan kepadatan siswa tinggi.</p><p>Setiap dapur baru wajib lulus sidak kesiapan operasional sebelum mulai mendistribusikan makanan.</p>',
    coverImage: cover('photo-1414235077428-338989a2e8c0'),
    regionId: '61',
    publishedAt: new Date('2026-06-18T15:30:00Z'),
    status: 'published' as const,
    isHighlight: false,
    isBreaking: false,
    tags: ['sppg', 'mbg', 'bgn', 'perluasan'],
  },
  {
    id: 'a1000012-0012-4012-8012-000000000012',
    title: 'Sidak BGN di Bali: Transparansi Pengelolaan Bahan Pangan',
    slug: 'sidak-bgn-bali-transparansi-bahan-pangan',
    category: 'sidak',
    content:
      '<p>Inspeksi BGN di 12 dapur SPPG Bali menekankan aspek transparansi rantai pasok bahan pangan. Tim memverifikasi asal-usul bahan, sertifikat halal, dan kesesuaian harga dengan anggaran Program MBG.</p><p>Seluruh dapur yang disidak dinilai telah menerapkan pencatatan bahan pangan yang memadai.</p>',
    coverImage: cover('photo-1546069901-ba9599a7e63c'),
    regionId: '51',
    publishedAt: new Date('2026-06-17T11:15:00Z'),
    status: 'published' as const,
    isHighlight: false,
    isBreaking: false,
    tags: ['sidak', 'sppg', 'bali', 'bgn'],
  },
  {
    id: 'a1000013-0013-4013-8013-000000000013',
    title: 'Studi Komparasi Model SPPG Desa vs Kota',
    slug: 'studi-komparasi-model-sppg-desa-vs-kota',
    category: 'laporan',
    content:
      '<p>BGN merilis studi komparasi antara model operasional dapur SPPG di wilayah desa dan perkotaan. Penelitian membandingkan efisiensi biaya, kualitas gizi, dan tantangan logistik distribusi.</p><p>Model desa unggul dalam pemanfaatan bahan pangan lokal, sementara model kota lebih efisien dalam skala produksi massal.</p>',
    coverImage: cover('photo-1517248135467-4c7edcad34c4'),
    regionId: '34',
    publishedAt: new Date('2026-06-16T09:00:00Z'),
    status: 'published' as const,
    isHighlight: false,
    isBreaking: false,
    tags: ['sppg', 'kajian', 'desa', 'kota'],
  },
  {
    id: 'a1000014-0014-4014-8014-000000000014',
    title: 'BGN Respons Temuan Kebersihan di Dapur SPPG Makassar',
    slug: 'bgn-respons-temuan-kebersihan-sppg-makassar',
    category: 'berita_umum',
    content:
      '<p>Badan Gizi Nasional merespons temuan kebersihan pada tiga dapur SPPG di Makassar yang viral di media sosial. Tim verifikasi BGN langsung turun ke lapangan dan memastikan perbaikan selesai dalam 48 jam.</p><p>BGN mengingatkan seluruh pengelola SPPG agar menjaga standar higienitas dan melaporkan kendala operasional kepada admin wilayah.</p>',
    coverImage: cover('photo-1565299624946-b28f40a0ae38'),
    regionId: '73',
    publishedAt: new Date('2026-06-15T16:00:00Z'),
    status: 'published' as const,
    isHighlight: false,
    isBreaking: false,
    tags: ['bgn', 'sppg', 'makassar', 'tindak-lanjut'],
  },
  {
    id: 'a1000015-0015-4015-8015-000000000015',
    title: 'Inspeksi Terpadu 120 SPPG Wilayah Sumatera',
    slug: 'inspeksi-terpadu-120-sppg-wilayah-sumatera',
    category: 'sidak',
    content:
      '<p>BGN melaksanakan inspeksi terpadu ke 120 dapur SPPG di lima provinsi Sumatera. Operasi gabungan melibatkan inspektor pusat, admin wilayah, dan ahli gizi daerah.</p><p>Fokus pemeriksaan meliputi standar gizi menu, keamanan pangan, dan kepatuhan terhadap juknis sidak SPPG terbaru.</p>',
    coverImage: cover('photo-1567620905732-2d1ec7ab7445'),
    regionId: '16',
    publishedAt: new Date('2026-06-14T08:45:00Z'),
    status: 'published' as const,
    isHighlight: false,
    isBreaking: false,
    tags: ['sidak', 'sppg', 'sumatera', 'mbg'],
  },
  {
    id: 'a1000016-0016-4016-8016-000000000016',
    title: 'Benchmarking Keamanan Pangan Antardaerah SPPG',
    slug: 'benchmarking-keamanan-pangan-antardaerah-sppg',
    category: 'laporan',
    content:
      '<p>Laporan benchmarking BGN membandingkan indikator keamanan pangan antardaerah pada jaringan SPPG nasional. Provinsi dengan skor tertinggi menunjukkan konsistensi pemantauan suhu dan pelatihan petugas berkala.</p><p>Hasil benchmarking akan menjadi acuan alokasi pembinaan teknis pada semester berikutnya.</p>',
    coverImage: cover('photo-1606787366850-de6330128bfc'),
    regionId: null,
    publishedAt: new Date('2026-06-12T10:30:00Z'),
    status: 'published' as const,
    isHighlight: false,
    isBreaking: false,
    tags: ['sppg', 'keamanan-pangan', 'kajian', 'bgn'],
  },
  {
    id: 'a1000017-0017-4017-8017-000000000017',
    title: 'MBG Perluas Cakupan ke 500 Kabupaten/Kota',
    slug: 'mbg-perluas-cakupan-500-kabupaten-kota',
    category: 'berita_umum',
    content:
      '<p>Program Makan Bergizi Gratis diperluas ke 500 kabupaten dan kota pada semester II 2026. BGN menyiapkan skema pendampingan operasional SPPG dan mekanisme sidak berkala di setiap wilayah baru.</p><p>Perluasan ini diharapkan menjangkau tambahan 4 juta penerima manfaat, terutama siswa sekolah dasar dan PAUD.</p>',
    coverImage: cover('photo-1533777857889-4be7c70b33f7'),
    regionId: null,
    publishedAt: new Date('2026-06-10T09:00:00Z'),
    status: 'published' as const,
    isHighlight: false,
    isBreaking: false,
    tags: ['mbg', 'perluasan', 'bgn', 'sppg'],
  },
  {
    id: 'a1000018-0018-4018-8018-000000000018',
    title: 'Sidak Follow-up: Dapur SPPG Bogor Lulus Verifikasi Ulang',
    slug: 'sidak-follow-up-sppg-bogor-lulus-verifikasi',
    category: 'sidak',
    content:
      '<p>Dapur SPPG Bogor yang sebelumnya mendapat rekomendasi perbaikan telah lulus verifikasi ulang BGN. Sidak follow-up memastikan seluruh temuan terkait sanitasi dan penyimpanan bahan pangan telah ditangani.</p><p>Dapur kembali beroperasi penuh dan melayani distribusi MBG untuk 12 sekolah di wilayah Bogor.</p>',
    coverImage: cover('photo-1555939594-58d7cb561ad1'),
    regionId: '32',
    publishedAt: new Date('2026-06-08T14:20:00Z'),
    status: 'published' as const,
    isHighlight: false,
    isBreaking: false,
    tags: ['sidak', 'sppg', 'bogor', 'verifikasi'],
  },
  {
    id: 'a1000019-0019-4019-8019-000000000019',
    title: 'Analisis Kepuasan Penerima Manfaat Program MBG',
    slug: 'analisis-kepuasan-penerima-manfaat-mbg',
    category: 'laporan',
    content:
      '<p>BGN merilis analisis kepuasan penerima manfaat Program MBG berdasarkan survei ke 2.000 sekolah. Responden menyatakan apresiasi terhadap kualitas rasa dan ketepatan waktu distribusi makanan dari dapur SPPG.</p><p>Masukan utama mencakup keinginan variasi menu lebih tinggi dan transparansi informasi gizi per porsi.</p>',
    coverImage: cover('photo-1490645935967-10de6ba17061'),
    regionId: '36',
    publishedAt: new Date('2026-06-05T11:00:00Z'),
    status: 'published' as const,
    isHighlight: false,
    isBreaking: false,
    tags: ['mbg', 'kepuasan', 'kajian', 'bgn'],
  },
  {
    id: 'a1000020-0020-4020-8020-000000000020',
    title: 'BGN Umumkan Jadwal Sidak Nasional SPPG Juli 2026',
    slug: 'bgn-jadwal-sidak-nasional-sppg-juli-2026',
    category: 'berita_umum',
    content:
      '<p>Badan Gizi Nasional mengumumkan jadwal Sidak Nasional SPPG yang akan digelar pada Juli 2026. Operasi akan menyasar 2.000 dapur SPPG di seluruh Indonesia dengan fokus kepatuhan standar gizi dan keamanan pangan Program MBG.</p><p>Hasil sidak akan dipublikasikan melalui Portal Sidak Pantau Terpadu untuk menjaga akuntabilitas publik.</p>',
    coverImage: cover('photo-1511690656952-343388bb7005'),
    regionId: null,
    publishedAt: new Date('2026-06-01T08:00:00Z'),
    status: 'published' as const,
    isHighlight: false,
    isBreaking: false,
    tags: ['bgn', 'sidak', 'sppg', 'nasional'],
  },
];
